config/routes.rb
Rails.application.routes.draw do


  get 'notifications/index'
  
  resources :orders 
# home page and about, contact page routes
  root 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/blog'
  get 'orders/contact'
  # order page
  get 'home/reserve'
  get 'home/firstcake'
  get 'home/secondcake'
  get 'home/thirdone'
  get 'home/fourthone'
  get 'home/fiveone'
  get 'home/sixone'
  get 'home/make'
  get 'home/sevenone'
  get 'home/eightone'
  get 'home/nineone'
  # next cake page routes
  get 'home/next'
  get 'home/next1'
  get 'home/next2'
  get 'home/next3'
  get 'home/next4'
  get 'home/next5'
  get 'home/next6'

  get 'home/testimonies'
 
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mane.rb
class Mane < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  rescue_from StandardError do |exception|
    trigger_sms_alerts(exception)
  end

  def trigger_sms_alerts(e)
    @alert_message = "
      [This is a test] ALERT! 
      It appears the server is having issues. 
      Exception: #{e}. 
      Go to: http://newrelic.com for more details."
    @image_url = "http://howtodocs.s3.amazonaws.com/new-relic-monitor.png"

    @admin_list = YAML.load_file('config/administrators.yml')

    begin
      @admin_list.each do |admin|
        phone_number = admin['phone_number']
        send_message(phone_number, @alert_message, @image_url)
      end
      
      flash[:success] = "Exception: #{e}. Administrators will be notified."
    rescue
      flash[:alert] = "Something when wrong."
    end


    redirect_to '/'
  end

  def index
  end

  def server_error
    raise 'A test exception'
  end

  private

    def send_message(phone_number, alert_message, image_url)

      @twilio_number = ENV['TWILIO_NUMBER']
      @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
      
      message = @client.account.messages.create(
        :from => @twilio_number,
        :to => phone_number,
        :body => alert_message,
        # US phone numbers can make use of an image as well.
        # :media_url => image_url 
      )
      puts message.to
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/about.html.erb
<div class="wrapper">
   <nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
    <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
       <li><a href="blog">Gallery</a></li>
       <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonial</a></li>
     <li><a href="contact">Contact</a></li>
     
     
    </ul>
  </div>
</nav>

		

 
    <h1 id="me">About Me</h1>
    <div class="container">

    <div class="row">
      <div class="col s6 push-s6"><span class="flow-text"> <div id="abouther"><h3> My Story</h3>
      	<p id="about1">
      		Hello There!!!*royal wave* My name is Cynthia. I’m a home baker whose passion for baking sweets, and breads derived from wanting to eat clean. Which led me to start baking low carb/paleo and vegan cakes. I am constantly driven by creative ideas,trying to create authentic sweets made from top notch ingredients. Lord knows, in this society, we need more pure/minimalistic ingredients in our day-to-day lives, and that's what I strive for. Essentially bringing back grandma's cooking/baking to the kitchen. It's no wonder grandma's cooking was the best...sorry mom lol..love you.
      		

      	</p></span></div></div>

      	<div class="col s6 pull-s6">
      		<span class="flow-text"> <%= image_tag("cynthia.png", :size => "300x400")  %>
      			<div id="abouther">
      			</span>
      			<p style="margin-top:-11px;">
      				Many describe my passion for the art of cakes/desserts as an" Explorer ". Because I add my own sassiness in all that I create, with not only organically grown ingredients but also using exotic fruits, creative food mashups, and multicultural inspirations. All that I create is made with pure love. Seeing a smile on a person's face after tasting something I've made is my ultimate goal.</p>
      				</div>
      		</div>
      	</div>
      	</div>
      	<div class="foot2">
<center>
<p style="color:white;">C.C.C</p><br>
<button class="waves-effect waves-light btn">
  <a href="">About</a>
  </button>
  <button class="waves-effect waves-light btn">
 <%= link_to 'Cake', orders_path %>
  </button class="waves-effect waves-light btn">
  <button class="waves-effect waves-light btn">
  <a href="make">Custom Cake</a>
  </button>
  <button class="waves-effect waves-light btn">
  <a href="contact">Contact</a>
  </button><br>
  <div>
    <a href=""></a>
  </div>
    <button class="waves-effect waves-light btn">
  <a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
   <button class="waves-effect waves-light btn">
  </a> &nbsp;&nbsp;
  <a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>
  </a>
  <h6 style="color:white">Made in © 2017 | Philco Michel</h6>
</button>
</center>


</div>

app/views/home/eightone.html.erb
 <nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
   <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
       <li><a href="blog">Gallery</a></li>
       <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonials</a></li>
     <li><a href="contact">Contact</a></li>
     
    </ul>
  </div>
</nav>
<div class="make">
<div class="learnmore">
	<div class="tit2">

		<h1> <span>B</span>arbell <span> P</span>late <span> C</span>ake</h1>
	</div>
	
		<div class="container">
			<div class="img_cutom">
				<%= image_tag("barbell.jpeg", :size => "660x680")  %> 

			</div>
			<div class="col s6">
				<div id="custom">
					<h3>Barbell Plate Cake</h3>
					<hr class="style18">
					<p>Gym rats and fitness gurus alike won't have enough of this cake! This cake has "hit the gym" written all over it! After one bite --gym heaven. Made of one "plate" of extra rhum butter cake layer that was soaked with rhum for three days to ensure sharpness. You'd definitely have to chase this down with HIIT and milk!! It's iced entirely with buttercream and than garnished with fondant details. Question, how much do you caddy?😜.
					</p>
					<h4>Ingredients</h4>
					<p>
						 Butter, sugar, free range eggs,lime zest, vanilla extract, buttermilk, salt, flour, baking powder, powdered sugar, barbacourt rhum sauce (for soaking).  </p>
						<hr class="style18">
						<div class="col s6 pull-s5">

						</div>
							
					</div>
				</div>
			</div>
		</div>
		<div id="back_ccc">
							<button> <%= link_to 'Back', orders_path %></button>
						</div>
	</div>
<div class="container">
	<div class="nxt-pic">
	<a href="sixone">	<%= image_tag("baby.png", :size => "360x480")  %> 		</a>
		<a href="sevenone"><%= image_tag("purse.jpeg", :size => "360x480")  %> 	</a>
		<a href="nineone"><%= image_tag("paris.jpeg", :size => "360x480", )  %>	</a>
		</div>
		</div>


	<div class="foot">
		<center>
			<p style="color:white;">C.C.C</p><br>
			<button class="waves-effect waves-light btn">
				<a href="">About</a>
			</button>
			<button class="waves-effect waves-light btn">
				<a href="">Cake</a>
			</button class="waves-effect waves-light btn">
			<button class="waves-effect waves-light btn">
				<a href="">Custom Cake</a>
			</button>
			<button class="waves-effect waves-light btn">
				<a href="">Contact</a>
			</button><br>
			<div>
				<a href=""></a>
			</div>
			<button class="waves-effect waves-light btn">
				<a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
				<button class="waves-effect waves-light btn">
				</a> &nbsp;&nbsp;
				<a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>

			</a>
			<h6 style="color:white">Made in FL 2017 Philco Michel </h6>
		</button>
	</center>


</div>

app/views/home/firstcake.html.erb
 <nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
    <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
       <li><a href="blog">Gallery</a></li>
       <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonials</a></li>
     
    </ul>
  </div>
</nav>

		
<div class="make">
<div class="learnmore">
	<div class="tit2">

		<h1><span>T</span>he <span> S</span>hirt <span> C</span>ake</h1>
	</div>
	
		<div class="container">
			<div class="img_cutom">
				<%= image_tag("tiecake.png", :size => "660x680")  %> 

			</div>
			<div class="col s6">
				<div id="custom">
					<h3>The Shirt Cake</h3>
					<hr class="style18">
					<p> This cake was made out of two decadently moist layers of delicious tropical brown butter carrot cake. That is smothered by luscious spiced cookie butter whipped cream cheese icing. The same irresistible icing covers the entire cake, than covered in LMF fondant. Garnished with a fondant tie, collar and pocket.
					</p>
					<h4>Ingredients</h4>
					<p>
						Butter, brown sugar

						Vanilla extract

						Free range eggs

						Orange zest/liquor 

						Undrained crushed pineapples 

						Raisins 

						Toasted Pecans 

						Desiccated coconut 

						Salt 

						Baking soda/ powder 

						Spice blend (cinnamon,nutmeg, ginger, all spice)

						Flour 

						Cream cheese 

						Cookie butter

						Powdered sugar

						LMF fondant </p>
						<hr class="style18">
						<div class="col s6 pull-s5">

						</div>
							
					</div>
				</div>
			</div>
		</div>
		<div id="back_ccc">
							<button> <%= link_to 'Back', orders_path %></button>
						</div>
	</div>
	<div class="container">
	<div class="nxt-pic">
	</a>
		<a href="secondcake"><%= image_tag("chacha.png", :size => "260x280", )  %>	</a>
	<a href="thirdone">	<%= image_tag("bee.jpg", :size => "260x280")  %> 		</a>
		<a href="fourthone"><%= image_tag("strike.png", :size => "260x280")  %> 	</a>
		</div>
		</div>

	<div class="foot">
		<center>
			<p style="color:white;">C.C.C</p><br>
			<button class="waves-effect waves-light btn">
				<a href="about">About</a>
			</button>
			<button class="waves-effect waves-light btn">
				<%= link_to 'Cakes', orders_path %>
			</button class="waves-effect waves-light btn">
			<button class="waves-effect waves-light btn">
				<a href="make">Custom Cake</a>
			</button>
			<button class="waves-effect waves-light btn">
				<a href="contact">Contact</a>
			</button><br>
			<div>
				<a href=""></a>
			</div>
			<button class="waves-effect waves-light btn">
				<a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
				<button class="waves-effect waves-light btn">
				</a> &nbsp;&nbsp;
				<a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>

			</a>
			<h6 style="color:white">Made in FL 2017 Philco Michel </h6>
		</button>
	</center>


</div>

app/views/home/fiveone.html.erb
<nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
    <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
       <li><a href="blog">Gallery</a></li>
       <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonials</a></li>
     
    </ul>
  </div>
</nav>

		
<div class="make">
<div class="learnmore">
	<div class="tit2">
	<h1><span>C</span>hocolate  <span> H</span>eart  <span> C</span>ake</h1>
	</div>
	
		<div class="container">
			<div class="img_cutom">
				<%= image_tag("valtime.png", :size => "660x680")  %> 

			</div>
			<div class="col s6">
				<div id="custom">
					<h3>Chocolate Heart Cake</h3>
					<hr class="style18">
					<p> This cake doesn't have to be celebrated only on holidays, but can also be used to treat yourself, friends or loved ones, celebrate accomplishments, and anniversaries. It's made with three moist gluten-free vanilla cake layers smothered by a deliciously smooth vanilla lime buttercream that also covers the entire cake. Garnished with fondant and assorted chocolates.



					</p>
					<h4>Ingredients</h4>
					<p>  butter, oil, vanilla/almond extract, sugar, lime zest, whole free range eggs, milk, almond/coconut flour, baking soda/powder, salt, and powdered sugar

</p>
						<hr class="style18">
						<div class="col s6 pull-s5">

						</div>
							
					</div>
				</div>
			</div>
		</div>
		<div id="back_ccc">
							<button> <%= link_to 'Back', orders_path %></button>
						</div>
	</div>

	<div class="container">
	<div class="nxt-pic">
			<a href="sixone">	<%= image_tag("baby.png", :size => "260x280")  %> 		</a>
		<a href="firstcake"><%= image_tag("tiecake.png", :size => "260x280")  %> 	</a>
			<a href="secondcake"><%= image_tag("chacha.png", :size => "260x280", )  %>	</a>
		</div>
		</div>


	<div class="foot">
		<center>
			<p style="color:white;">C.C.C</p><br>
			<button class="waves-effect waves-light btn">
				<a href="about">About</a>
			</button>
			<button class="waves-effect waves-light btn">
				<%= link_to 'Cakes', orders_path %>
			</button class="waves-effect waves-light btn">
			<button class="waves-effect waves-light btn">
				<a href="make">Custom Cake</a>
			</button>
			<button class="waves-effect waves-light btn">
				<a href="contact">Contact</a>
			</button><br>
			<div>
				<a href=""></a>
			</div>
			<button class="waves-effect waves-light btn">
				<a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
				<button class="waves-effect waves-light btn">
				</a> &nbsp;&nbsp;
				<a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>

			</a>
			<h6 style="color:white">Made in FL 2017 Philco Michel </h6>
		</button>
	</center>


</div>

app/views/home/fourthone.html.erb
 <nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
    <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
       <li><a href="blog">Gallery</a></li>
       <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonials</a></li>
     
    </ul>
  </div>
</nav>
<div class="make">
<div class="learnmore">
	<div class="tit2">

		<h1><span>B</span>owling <span> B</span>all <span> C</span>ake</h1>
	</div>
	
		<div class="container">
			<div class="img_cutom">
				<%= image_tag("strike.png", :size => "660x680")  %> 

			</div>
			<div class="col s6">
				<div id="custom">
					<h3>Bowling Ball Cake</h3>
					<hr class="style18">
					<p> Is sure to please any crowd. It has two components that will make anyone with a sweet tooth drool-ice cream cake! Made with my signature rich homemade vanilla and Oreo crumble ice cream that is strategically placed in the center of two moist cookies n cream cake layers. Separated by a decadent homemade chocolate magic sauce to keep the ice cream from oozing out of the cake layers making it difficult to cut. Covered entirely with whipped raspberry flavored ganache followed by fondant. Garnished with fondant bowling pins and light stand.



					</p>
					<h4>Ingredients</h4>
					<p>
						Butter, Coconut oil, free range egg whites, sugar, vanilla, heavy whipping cream, milk, flour, baking soda, salt, Oreos, semi-sweet/milk chocolate chips

 
 </p>
						<hr class="style18">
						<div class="col s6 pull-s5">

						</div>
							
					</div>
				</div>
			</div>
		</div>
		<div id="back_ccc">
							<button> <%= link_to 'Back', orders_path %></button>
						</div>
	</div>
	<div class="container">
	<div class="nxt-pic">
		<a href="fiveone"><%= image_tag("valtime.png", :size => "260x280", )  %>	</a>
			<a href="sixone">	<%= image_tag("baby.png", :size => "260x280")  %> 		</a>

		<a href="firstcake"><%= image_tag("tiecake.png", :size => "260x280")  %> 	</a>
		</div>
		</div>


	<div class="foot">
		<center>
			<p style="color:white;">C.C.C</p><br>
			<button class="waves-effect waves-light btn">
				<a href="about">About</a>
			</button>
			<button class="waves-effect waves-light btn">
				<%= link_to 'Cakes', orders_path %>
			</button class="waves-effect waves-light btn">
			<button class="waves-effect waves-light btn">
				<a href="make">Custom Cake</a>
			</button>
			<button class="waves-effect waves-light btn">
				<a href="contact">Contact</a>
			</button><br>
			<div>
				<a href=""></a>
			</div>
			<button class="waves-effect waves-light btn">
				<a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
				<button class="waves-effect waves-light btn">
				</a> &nbsp;&nbsp;
				<a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>

			</a>
			<h6 style="color:white">Made in FL 2017 Philco Michel </h6>
		</button>
	</center>


</div>

app/views/home/index.html.erb
<div class="home1">
 <nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <ul id="menu">
     <li><a href="index">Home</a></li>
     <li><a href="about">About</a></li>
     <li><%= link_to 'Cakes', orders_path %> </li>
     <li><a href="blog">Gallery</a></li>
     <li><a href="make">Custom Cake</a></li>
     <li><a href="testimonies">Testimonials</a></li>
     <li><a href="contact">Contact</a></li>
    </ul>
  </div>
 </nav>
<!--Nav-bar end -->
<!-- main title -->
<div class="container">
  <div class="tit">
    <h1><span>C</span>ynthia <span>C</span>outure <span>C</span>akes</h1>
  </div>
  <p class="b"> Bakery Needs For All Occassions </p>
  <p class="p">Homemade & Organically Delicious</p>
</div>

<!-- end -->
<!-- slide image show -->
<div class="wapper1">
 <div class="details">
  <a  class="btn btn-primary btn-block btn-large"> Live well with CCC.</a>
</div>
<div class="slider">
  <ul class="slides">
    <li>
      <%= image_tag("cyn5.jpg", height:'270', width: '400',)  %> 
      <div class="caption center-align" style="color:white ">
        <h2>Cupcake Banquets</h2>
        <h4 class="phrase1">Order any size and style</h4>
      </div>
    </li>
    <li>
      <%= image_tag("sweet.jpg")  %><!-- random image -->
      <div class="caption left-align" style="color: #8B8989">
        <h2>French Macarons</h2>
        <h4 class="phrase">Decadent melt-in-your-mouth cookies</h4>
      </div>
    </li>
    <li>
     <%= image_tag("rescake4.jpg") %> <!-- random image -->
     <div class="caption right-align" style="color:#2fcaf9">
      <h1>Vegan/Primal/Paleo Friendly!</h1>
      <h4 class="phrase2">Nutrient densed sweets</h4>
    </div>
  </li>
  <li>
   <%= image_tag("partycake.jpg", height:'270', width: '400',)  %><!-- random image -->
   <div class="caption center-align" style="color: #808080">
    <h1>Cake Pops</h1>
    <h4 class="phrase">Elegant party treats</h4>
  </div>
</li>
</ul>
</div>
<!-- siled end here -->

<!-- a bits of about me  -->
<div class="wrapper">
  <h1 id="me">About Me</h1>
  <div class="container">
    <div class="row">
      <div class="col s5 push-s7"><span class="flow-text"> <div id="abouther">
        <p id="about1">
          Many describe my passion for the art of cakes/desserts as an" Explorer ". Because I add my own sassiness in all that I create, with not only organically grown ingredients but also using exotic fruits, creative food mashups, and multicultural inspirations. All that I create is made with pure love. Seeing a smile on a person's face after tasting something I've made is my ultimate goal. 

        </p></span></div></div>

        <div class="col s6 pull-s5"><span class="flow-text"> <%= image_tag("cynthia.png", :size => "360x580")  %>
          <div id="abouther">
          </span>
        </div>
      </div>
    </div>
  </div>
  <!-- about me end here -->
  <!-- footer -->
  <div class="foot">
    <center>
      <p style="color:white;">C.C.C</p><br>
      <button class="waves-effect waves-light btn">
        <a href="about">About</a>
      </button>
      <button class="waves-effect waves-light btn">
        <%= link_to 'Cakes', orders_path %>
      </button class="waves-effect waves-light btn">
      <button class="waves-effect waves-light btn">
        <a href="make">Custom Cake</a>
      </button>
      <button class="waves-effect waves-light btn">
        <a href="contact">Contact</a>
      </button><br>
      <div>
        <a href=""></a>
      </div>
      <button class="waves-effect waves-light btn">
        <a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i></a></button>
        <button class="waves-effect waves-light btn">
        </a> &nbsp;&nbsp;
        <a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true"></i></a></button>

      </a>
      <h6 style="color:white">Made in © 2017 | Philco Michel</h6>
    </button>
  </center>
</div>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/new.html.erb
<header class="ccheader">
    <h1>Make It Your Way.</h1>	
</header>
<div class="wrapper">
    <form method="post" action="" class="ccform">
    <div class="ccfield-prepend">
        <input class="ccformfield" type="text" placeholder="Full Name" required>
    </div>
    <div class="ccfield-prepend">
        <input class="ccformfield" type="text" placeholder="Email" required>
    </div>
    <div class="ccfield-prepend">
        <input class="ccformfield" type="text" placeholder="Phone">
    </div>
     <div class="ccfield-prepend">
        <input class="ccformfield" type="text" placeholder="Subject" required>
    </div>
    <div class="ccfield-prepend">
        <textarea class="ccformfield" name="comments" rows="8" placeholder="Message" required></textarea>
    </div>
    <div class="ccfield-prepend">
        <input class="ccbtn" type="submit" value="Submit">
    </div>
    </form>
</div>

<!-- <#%= render 'form', order: @order %> -->
<div id="new">
<button>
<%= link_to 'Back', orders_path %></button>
</div>
<buttom>
<%= link_to 'New User', new_user_path %>
</buttom>




<div class="icon">
<a href="https://www.instagram.com/cynthia_couture_cakes/?hl=en"><i class="fa fa-instagram" aria-hidden="true">IG</i>
</a> &nbsp;&nbsp;
<a href="https://www.facebook.com/profile.php?id=100013551661548"><i class="fa fa-facebook" aria-hidden="true">Book</i>
</a
</a> &nbsp;&nbsp;
<a href="orders/home/contact"><i class="fa fa-envelope" aria-hidden="true"></i>
</a>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>